logger.dir: /home/admin/logs/healthps
app:
    name: dubbotest


#dubbo config
dubbo:
    registry.url: 127.0.0.1:2181
    export:
        port: 20880
        version: LATEST
        retries: 0
        timeout: 5000
    reference:
        timeout: 5000
        check: false
        retries: 0
